-- Fresh PostgreSQL database only. Generated from Hibernate mappings; never run on an existing populated schema.
create table chat_rooms (is_private boolean not null, max_members smallint not null, target_year smallint, created_at timestamp(6) with time zone not null, deleted_at timestamp(6) with time zone, updated_at timestamp(6) with time zone not null, created_by uuid, id uuid not null, room_name varchar(100) not null, description varchar(500), password_hash varchar(255), room_type varchar(255) not null check ((room_type in ('GROUP','DIRECT'))), primary key (id));
create table friend_requests (created_at timestamp(6) with time zone not null, responded_at timestamp(6) with time zone, id uuid not null, receiver_id uuid not null, sender_id uuid not null, status varchar(255) not null check ((status in ('PENDING','ACCEPTED','DECLINED'))), primary key (id));
create table friendships (created_at timestamp(6) with time zone not null, friend_id uuid not null, id uuid not null, user_id uuid not null, nickname varchar(100), primary key (id));
create table interests (is_active boolean not null, created_at timestamp(6) with time zone not null, id uuid not null, name varchar(100) not null unique, primary key (id));
create table messages (created_at timestamp(6) with time zone not null, deleted_at timestamp(6) with time zone, updated_at timestamp(6) with time zone not null, id uuid not null, room_id uuid not null, sender_id uuid not null, content text not null, message_type varchar(255) not null check ((message_type in ('TEXT','IMAGE','FILE'))), primary key (id));
create table notifications (is_read boolean not null, created_at timestamp(6) with time zone not null, actor_user_id uuid, friend_request_id uuid, id uuid not null, room_id uuid, user_id uuid not null, type varchar(30) not null check ((type in ('FRIEND_REQUEST','NEW_MESSAGE','ROOM_INVITE','SYSTEM'))), message text, title varchar(255), primary key (id));
create table random_chat_messages (created_at timestamp(6) with time zone not null, deleted_at timestamp(6) with time zone, updated_at timestamp(6) with time zone not null, id uuid not null, sender_id uuid not null, session_id uuid not null, content text not null, message_type varchar(255) not null check ((message_type in ('TEXT','IMAGE','FILE'))), primary key (id));
create table random_chat_sessions (ended_at timestamp(6) with time zone, matched_at timestamp(6) with time zone, started_at timestamp(6) with time zone not null, ended_by_user_id uuid, id uuid not null, user1_id uuid not null, user2_id uuid, status varchar(255) not null check ((status in ('WAITING','MATCHED','ENDED','CANCELLED'))), primary key (id));
create table room_interests (interest_id uuid not null, room_id uuid not null, primary key (interest_id, room_id));
create table room_members (joined_at timestamp(6) with time zone not null, last_read_at timestamp(6) with time zone, left_at timestamp(6) with time zone, id uuid not null, room_id uuid not null, user_id uuid not null, role varchar(255) not null check ((role in ('OWNER','MODERATOR','MEMBER'))), primary key (id));
create table user_gallery_photos (photo_order integer not null check ((photo_order>=0)), user_id uuid not null, image_url varchar(2048) not null, primary key (photo_order, user_id));
create table user_interests (interest_id uuid not null, user_id uuid not null, primary key (interest_id, user_id));
create table user_profiles (user_id uuid not null, bio varchar(500), primary key (user_id));
create table users (date_of_birth date, year smallint, created_at timestamp(6) with time zone not null, last_seen_at timestamp(6) with time zone, updated_at timestamp(6) with time zone not null, id uuid not null, bio varchar(500), department varchar(255), email varchar(255) not null unique, firstname varchar(255), image_url varchar(255), lastname varchar(255), password_hash varchar(255) not null, status varchar(255) not null check ((status in ('ACTIVE','BLOCKED'))), primary key (id));
alter table if exists chat_rooms add constraint FKin9277aywbjursj2b4e3bmw3s foreign key (created_by) references users;
alter table if exists friend_requests add constraint FKtcmqalc5v4qdt1slgcsa544i5 foreign key (receiver_id) references users;
alter table if exists friend_requests add constraint FKcchlh48b4347amfvmke793bg7 foreign key (sender_id) references users;
alter table if exists friendships add constraint FKt0mh1j446gu5rqba17rnknuil foreign key (friend_id) references users;
alter table if exists friendships add constraint FK4mcscxflf13uk72aupf6uwbgn foreign key (user_id) references users;
alter table if exists messages add constraint FKj9tydtks7eq8dy1jq67yv5icx foreign key (room_id) references chat_rooms;
alter table if exists messages add constraint FK4ui4nnwntodh6wjvck53dbk9m foreign key (sender_id) references users;
alter table if exists notifications add constraint FKc8j0u0suv08ytbh1lamjb5n28 foreign key (actor_user_id) references users;
alter table if exists notifications add constraint FKjq2eosrp7o8kxgip8skk807g0 foreign key (friend_request_id) references friend_requests;
alter table if exists notifications add constraint FK4itpwhwh4ce4uwaqod9jy1vjh foreign key (room_id) references chat_rooms;
alter table if exists notifications add constraint FK9y21adhxn0ayjhfocscqox7bh foreign key (user_id) references users;
alter table if exists random_chat_messages add constraint FK4jokql18ybobcsirohansatab foreign key (sender_id) references users;
alter table if exists random_chat_messages add constraint FKlpy045alhp9kgedh6bto03tsc foreign key (session_id) references random_chat_sessions;
alter table if exists random_chat_sessions add constraint FKneaj5mlji6nhk7x45f6mbdieq foreign key (ended_by_user_id) references users;
alter table if exists random_chat_sessions add constraint FK96oyibxdvoyj4po652w0rxtyx foreign key (user1_id) references users;
alter table if exists random_chat_sessions add constraint FKpue0b1tdg2kw0ymri0otqcmla foreign key (user2_id) references users;
alter table if exists room_interests add constraint FK3o3jhy3r0d43us8k5rbdwd0t5 foreign key (interest_id) references interests;
alter table if exists room_interests add constraint FKk722c2q7vcog6oh1a24ri7lg3 foreign key (room_id) references chat_rooms;
alter table if exists room_members add constraint FKy8xflbqhdc45qrm39ugks24t foreign key (room_id) references chat_rooms;
alter table if exists room_members add constraint FKmcymqhedxe30d98p07eeqo3my foreign key (user_id) references users;
alter table if exists user_gallery_photos add constraint FKmhf95225sbtshxn5tusp851p5 foreign key (user_id) references users;
alter table if exists user_interests add constraint FK8h2mk04o9ctuoqvntl29chtcm foreign key (interest_id) references interests;
alter table if exists user_interests add constraint FKdv9fflrh61wyuujfwx2yn1tb4 foreign key (user_id) references users;
alter table if exists user_profiles add constraint FKjcad5nfve11khsnpwj1mv8frj foreign key (user_id) references users;

create index if not exists ix_room_members_room_active on room_members(room_id, left_at);
create index if not exists ix_room_members_user_active on room_members(user_id, left_at);
create index if not exists ix_messages_room_created on messages(room_id, created_at desc) where deleted_at is null;
create index if not exists ix_notifications_user_read on notifications(user_id, is_read, created_at desc);
create index if not exists ix_friend_requests_receiver_status on friend_requests(receiver_id, status);
create index if not exists ix_friend_requests_sender_status on friend_requests(sender_id, status);
create index if not exists ix_friendships_user on friendships(user_id);
create index if not exists ix_friendships_friend on friendships(friend_id);
create index if not exists ix_chat_rooms_discovery on chat_rooms(room_type, deleted_at, created_at desc);
create index if not exists ix_user_interests_interest on user_interests(interest_id);
